### ISSUE TITLE
m_hunt.stan is missing

### ISSUE THREAD

**Issue by babeheim** [erik-ringen/phylo-foodsharing#1]
Hi Erik,

The file m_hunt.stan referenced in the line `fit_m_hunt <- stan(file="m_hunt.stan", data=data_list, chains=3, cores=3, control=list(adapt_delta=0.96), iter=2000, init="0" )
` is missing.

**Comment by babeheim** [comment]
Also the file EA.json

**Comment by erik-ringen** [comment]
Thanks, Brett! I've added those to the repo.
